// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package follow

import (
	"github.com/0x726f6f6b6965/follow/internal/config"
	"github.com/0x726f6f6b6965/follow/internal/services"
	"github.com/0x726f6f6b6965/follow/internal/storage/cache"
	"github.com/0x726f6f6b6965/follow/internal/storage/follower"
	"github.com/0x726f6f6b6965/follow/internal/storage/user"
	"github.com/0x726f6f6b6965/follow/pkg/logger"
	"github.com/0x726f6f6b6965/follow/protos/follow/v1"
	"github.com/redis/go-redis/v9"
	"github.com/tylertreat/BoomFilters"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitFollowService(cfg *config.AppConfig, db *gorm.DB, rds *redis.Client, filter *boom.CountingBloomFilter) (v1.FollowServiceServer, func(), error) {
	sotrageUsers := user.New(db)
	sotrageFollowers := follower.New(db)
	cacheCache := cache.New(rds)
	duration := getTTL(cfg)
	loggerLogConfig := logConfig(cfg)
	zapLogger, cleanup, err := logger.NewLogger(loggerLogConfig)
	if err != nil {
		return nil, nil, err
	}
	followServiceServer := services.NewFollowService(sotrageUsers, sotrageFollowers, cacheCache, duration, filter, zapLogger)
	return followServiceServer, func() {
		cleanup()
	}, nil
}
