// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"github.com/0x726f6f6b6965/follow/app/api/router"
	"github.com/0x726f6f6b6965/follow/app/api/services"
	v1_2 "github.com/0x726f6f6b6965/follow/protos/follow/v1"
	"github.com/0x726f6f6b6965/follow/protos/user/v1"
)

// Injectors from wire.go:

func InitRouter(user v1.UserServiceServer, follow v1_2.FollowServiceServer) (router.Router, error) {
	userAPI := services.NewUserAPI(user)
	followAPI := services.NewFollowAPI(follow)
	routerRouter := router.NewRouter(userAPI, followAPI)
	return routerRouter, nil
}
